// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfQv8HkFSskjxxJ6Jg-P7tF8XZIIosYo',
    appId: '1:911539254480:web:149e8ea92acba00d9f9ad5',
    messagingSenderId: '911539254480',
    projectId: 'my-notes-fb-f7e7f',
    authDomain: 'my-notes-fb-f7e7f.firebaseapp.com',
    storageBucket: 'my-notes-fb-f7e7f.appspot.com',
    measurementId: 'G-0GC7VFWVR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREBWdAEoEVrCh7K3N5uL1p1048paMZmw',
    appId: '1:911539254480:android:7f9bf580b69efdbf9f9ad5',
    messagingSenderId: '911539254480',
    projectId: 'my-notes-fb-f7e7f',
    storageBucket: 'my-notes-fb-f7e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZvKmXNjaOrQFc3RIgJeNGMvOV3OurWoA',
    appId: '1:911539254480:ios:59c2bd1e6784375a9f9ad5',
    messagingSenderId: '911539254480',
    projectId: 'my-notes-fb-f7e7f',
    storageBucket: 'my-notes-fb-f7e7f.appspot.com',
    iosClientId: '911539254480-au8ojt0es92pk708j5agdisu214dfd6e.apps.googleusercontent.com',
    iosBundleId: 'com.vikassingh',
  );
}
